# Generated by Django 4.1.5 on 2023-01-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=150)),
                ('Department', models.CharField(max_length=150)),
                ('DateOfJoining', models.DateTimeField()),
                ('PhotoFileName', models.CharField(max_length=150)),
            ],
        ),
    ]
